# Geochronology Calculations

In [1]:
import matplotlib.pyplot as plt
from bokeh.plotting import figure, output_notebook, show
from bokeh.layouts import column
from bokeh.models import Range1d, LinearAxis, ColumnDataSource, LabelSet, Span, Slope, Label, Legend

from scipy.interpolate import CubicSpline
import pandas as pd
import numpy as np
from IPython.core.display import display, HTML
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
output_notebook()

import geochron_apps as gc

Loading BokehJS ...

<center><img src="images/geochronology.png" align="center">
https://www.explainxkcd.com/wiki/index.php/1829:_Geochronology
</center>

The following presentation shows some of the geochronology calculations learned in the Advanced Geochronology class at University of Saskatchewan taught by Bruce Eglington and Camille Partin, 2021. Some of the images in this presentation are taken from lectures given by the instructor.

This notebook contains sample calculations typically used in geochronology. It can be obtained at https://git.cs.usask.ca/msv275/advanced-geochronology.  
It can be cloned through the git command:  
* git clone https://git.cs.usask.ca/msv275/advanced-geochronology.git


## Pb-Pb Calculations

For the following calcuations, the equation used to calculate compositions is the isochron equation:  


present day ratio = initial ratio + parent/daughter ratio * (*e*<sup>λ x t1</sup> - *e*<sup>λ x t2</sup>)  


We can make a function that we can use whenever we need this equation.

Assume an initial 206Pb/204Pb starting composition of **16.0** and 238U/204Pb values of **0.1, 2.0, 9.74 and 50.0** for rocks and minerals formed at **2000** Ma.  
Calculate their present day 206Pb/204Pb compositions.

For this we know:  
* initial = 16.0  
* pd_ratios = 0.1,2.0,9.74, and 50
* decay_const = 1.55125 x 10<sup>-10</sup>
* t1 = 2000 Ma
* t2 = 0 present day (we don't need to enter a number as this is the default)
So we can simply make a list for the pd_ratios, run it through a for loop, and calculate the present day composition!

In [2]:
initial = 16
pd_list = [0.1,2.0,9.74,50.0]
Pb_Pb = []
decay_const = 1.55125*10**-10
t1 = 2000
for pd_ratio in pd_list:
    Pb_Pb.append(gc.calc_t2_daughter(initial, pd_ratio, decay_const, t1,))
df = pd.DataFrame()
df['238U/204Pb'] = pd_list
df['206Pb/204Pb'] = Pb_Pb
df

238U/204Pb  206Pb/204Pb
0        0.10    16.036377
1        2.00    16.727532
2        9.74    19.543081
3       50.00    34.188301

Assume an initial <sup>206</sup>Pb/<sup>204</sup>Pb starting composition of 16.0 and <sup>238</sup>U/<sup>204</sup>Pb values of 0.1, 2.0, 9.74 and 50.0 for rocks and minerals formed at 2000 Ma. Calculate their present day <sup>206</sup>Pb/<sup>204</sup>Pb compositions.

We use our isochron equation. (Note: This is a duplicate question.)

In [3]:
initial = 16
pd_list = [0.1,2.0,9.74,50.0]
Pb_Pb = []
decay_const_238 = 1.55125*10**-10
t1 = 2000
for pd_ratio in pd_list:
    Pb_Pb.append(gc.calc_t2_daughter(initial, pd_ratio, decay_const_238, t1,))
df = pd.DataFrame()
df['238U/204Pb'] = pd_list
df['206Pb/204Pb'] = Pb_Pb
df

238U/204Pb  206Pb/204Pb
0        0.10    16.036377
1        2.00    16.727532
2        9.74    19.543081
3       50.00    34.188301

Calculate their positions at 500 Ma.

In [4]:
initial = 16
pd_list = [0.1,2.0,9.74,50.0]
Pb_Pb = []
decay_const_238 = 1.55125*10**-10
t1 = 2000
t2 = 500
for pd_ratio in pd_list:
    Pb_Pb.append(gc.calc_t2_daughter(initial, pd_ratio, decay_const_238, t1, t2))
df = pd.DataFrame()
df['238U/204Pb'] = pd_list
df['206Pb/204Pb'] = Pb_Pb
df

238U/204Pb  206Pb/204Pb
0        0.10    16.028312
1        2.00    16.566232
2        9.74    18.757552
3       50.00    30.155812

Calculate 235U/204Pb equivalents of each ratio in the first bullet and repeat the calculations for 2000 Ma and 500 Ma for the 235U-207Pb isotope system.

In [5]:
initial = 16
pd_list = [0.1,2.0,9.74,50.0]
Pb_Pb = []
decay_const_235 = 9.8485*10**-10
t1 = 2000
for pd_ratio in pd_list:
    Pb_Pb.append(gc.calc_t2_daughter(initial, pd_ratio, decay_const_235, t1,))
df = pd.DataFrame()
df['235U/204Pb'] = pd_list
df['207Pb/204Pb'] = Pb_Pb
df

235U/204Pb  207Pb/204Pb
0        0.10    16.616853
1        2.00    28.337051
2        9.74    76.081439
3       50.00   324.426280

In [6]:
initial = 16
pd_list = [0.1,2.0,9.74,50.0]
Pb_Pb = []
decay_const_235 = 9.8485*10**-10
t1, t2 = 2000, 500
for pd_ratio in pd_list:
    Pb_Pb.append(gc.calc_t2_daughter(initial, pd_ratio, decay_const_235, t1, t2))
df = pd.DataFrame()
df['235U/204Pb'] = pd_list
df['207Pb/204Pb'] = Pb_Pb
df

235U/204Pb  207Pb/204Pb
0        0.10    16.553225
1        2.00    27.064492
2        9.74    69.884078
3       50.00   292.612311

Assume a starting composition equivalent to the Stacey and Kramers (1975) model at 3.7 Ga. Calculate model Pb-Pb curves for uranogenic and thorogenic lead for 238U/204Pb values of **9.0**, **9.74** and **13.0** from 3.7 Ga to present day.

We use the isochron equation for our 206Pb/204Pb, and initial 206Pb/204Pb from Stacey and Kramers (1975) = **11.152**

Then we use 207Pb/204Pb<sub>p</sub> = 207Pb/204Pb<sub>i</sub> + 235U/238U<sub>p</sub> * 238U/204Pb<sub>p</sub> * (*e*<sup>λ t<sub>1</sub></sup> – *e*<sup>λt<sub>2</sub></sup>)  
* 207Pb/204Pb<sub>i</sub> = **12.998** from Stacey and Kramers (1975)
* 235U/238U<sub>p</sub> = **1/137.88**

Then we use 208Pb/204Pb<sub>p</sub> = 208Pb/204Pb<sub>i</sub> + 232Th/238U<sub>p</sub> * 238U/204Pb<sub>p</sub> * (*e*<sup>λ t<sub>1</sub></sup> – *e*<sup>λt<sub>2</sub></sup>)
* 208Pb/204Pb(initial) = **31.23** from Stacey and Kramers (1975)
* 232Th/238U depends on the source:
    - Depleted Upper Mantle = **2.5**
    - Ocean Island Basalts = **3.75**
    - Lower Mantle = **4**
    - Continental Crust = **5** Paul, White, and Turcotte (2003)

In [7]:
decay_const_238 = 1.55125*10**-10
decay_const_235 = 9.8485*10**-10
decay_const_232 = 4.9745*10**-11
U238U235 = 137.88
Pb206_initial = 11.152
Pb207_initial = 12.988
Pb208_initial = 31.23
kappa = 4

mu9_df = gc.get_PbPb_ratio_data(9.0, kappa)
mu974_df = gc.get_PbPb_ratio_data(9.74, kappa)
mu13_df = gc.get_PbPb_ratio_data(13, kappa)
mu9_df

t1    t2  238U/204Pb  206Pb/204Pb  207Pb/204Pb  208Pb/204Pb
3699  3700  3699         9.0    11.154478    12.990457    31.232153
3698  3700  3698         9.0    11.156956    12.992912    31.234305
3697  3700  3697         9.0    11.159434    12.995364    31.236458
3696  3700  3696         9.0    11.161911    12.997814    31.238610
3695  3700  3695         9.0    11.164388    13.000262    31.240762
...    ...   ...         ...          ...          ...          ...
4     3700     4         9.0    18.124003    15.418709    38.497851
3     3700     3         9.0    18.125400    15.418773    38.499642
2     3700     2         9.0    18.126797    15.418838    38.501433
1     3700     1         9.0    18.128193    15.418902    38.503224
0     3700     0         9.0    18.129589    15.418966    38.505015

[3700 rows x 6 columns]

Now let's plot some Pb/Pb curves.

In [8]:
figure5 = gc.get_figure("207Pb/204Pb - 206Pb/204Pb Curve", "207Pb/204Pb", "206Pb/204Pb", [10,22], [12,17])

gc.plot_uranogenicPb_curve(figure5, mu9_df, "red", "mu = 9.0")
gc.plot_uranogenicPb_curve(figure5, mu974_df, "blue", "mu = 9.74")
gc.plot_uranogenicPb_curve(figure5, mu13_df, "green", "mu = 13.0")

figure5.legend.location = "top_left"
figure5.legend.click_policy="hide"

In [9]:
show(figure5)

In [10]:
figure6 = gc.get_figure("208Pb/204Pb - 206Pb/204Pb Curve", "208Pb/204Pb", "206Pb/204Pb", [10,22], [30,42])

gc.plot_thorogenicPb_curve(figure6,mu9_df,"red", "mu = 9.0")
gc.plot_thorogenicPb_curve(figure6,mu974_df,"blue", "mu = 9.74")
gc.plot_thorogenicPb_curve(figure6,mu13_df,"green", "mu = 13.0")

figure6.legend.location = "top_left"
figure6.legend.click_policy="hide"

In [11]:
show(figure6)

Assume that the more lower crustal of these curves had a lot of uranium introduced at 1000 Ma, resulting in a change of 238U/204Pb to 500.0. Plot the evolution curve and determine the present day composition.

In [12]:
d2 = []
mu_list = [9.0, 9.74, 13.0]
model_mu = 500
t1, t2 = 3700, 1000
for mu in mu_list:
    t1, t2 = 1000, 0
    while t2 < 1000:
        if mu == 9:
            Pb208_initial = mu9_df[mu9_df['t2'] == 1000].values[0][-1]
            Pb206_initial = mu9_df[mu9_df['t2'] == 1000].values[0][-3]
        elif mu == 9.74:
            Pb208_initial = mu974_df[mu974_df['t2'] == 1000].values[0][-1]
            Pb206_initial = mu974_df[mu974_df['t2'] == 1000].values[0][-3]
        elif mu == 13:
            Pb208_initial = mu13_df[mu13_df['t2'] == 1000].values[0][-1]
            Pb206_initial = mu13_df[mu13_df['t2'] == 1000].values[0][-3]
        d2.append({'t1': t1,
            't2': t2,
            'original_initial': mu,
            '238U/204Pb': model_mu, 
            '206Pb/204Pb': gc.calc_t2_daughter(Pb206_initial, model_mu, decay_const_238, t1, t2),
            '207Pb/204Pb': gc.calc_t2_daughter(Pb207_initial, mu/U238U235, decay_const_235, t1, t2),
            '208Pb/204Pb': gc.calc_t2_daughter(Pb208_initial, kappa * mu, decay_const_232, t1, t2),
                 })
        t2 = t2 + 1
        
new_df = pd.DataFrame(d2)
adj_mu9_df = new_df[new_df['original_initial'] == 9].sort_values(by='206Pb/204Pb')
adj_mu974_df = new_df[new_df['original_initial'] == 9.74].sort_values(by='206Pb/204Pb')
adj_mu13_df = new_df[new_df['original_initial'] == 13].sort_values(by='206Pb/204Pb')

In [13]:
figure7 = gc.get_figure("208Pb/204Pb - 206Pb/204Pb Curve", "208Pb/204Pb", "206Pb/204Pb", [0,100], [36,42])

gc.plot_thorogenicPb_curve(figure7,adj_mu9_df,"red", "mu = 9.0")
gc.plot_thorogenicPb_curve(figure7,adj_mu974_df,"blue", "mu = 9.74")
gc.plot_thorogenicPb_curve(figure7,adj_mu13_df,"green", "mu = 13.0")

figure7.legend.location = "top_left"
figure7.legend.click_policy="hide"

In [14]:
show(figure7)

This shows both the original and evolution curves.

In [15]:
figure8 = gc.get_figure("208Pb/204Pb - 206Pb/204Pb Curve", "208Pb/204Pb", "206Pb/204Pb", [0,100], [30,42])

gc.plot_thorogenicPb_curve(figure8,mu9_df,"red", "mu = 9.0")
gc.plot_thorogenicPb_curve(figure8,mu974_df,"blue", "mu = 9.74")
gc.plot_thorogenicPb_curve(figure8,mu13_df,"green", "mu = 13.0")
gc.plot_thorogenicPb_curve(figure8,adj_mu9_df,"red", "mu = 9.0")
gc.plot_thorogenicPb_curve(figure8,adj_mu974_df,"blue", "mu = 9.74")
gc.plot_thorogenicPb_curve(figure8,adj_mu13_df,"green", "mu = 13.0")

figure8.legend.location = "top_left"
figure8.legend.click_policy="hide"

In [16]:
show(figure8)

And the present day compositions for each initial composition.

In [17]:
adj_mu9_df.tail(1)

t1  t2  original_initial  238U/204Pb  206Pb/204Pb  207Pb/204Pb  208Pb/204Pb
0  1000   0               9.0         500   100.521318    13.097492    38.505015

In [18]:
adj_mu974_df.tail(1)

t1  t2  original_initial  238U/204Pb  206Pb/204Pb  207Pb/204Pb  208Pb/204Pb
1000  1000   0              9.74         500   100.970856    13.106494    39.103182

In [19]:
adj_mu13_df.tail(1)

t1  t2  original_initial  238U/204Pb  206Pb/204Pb  207Pb/204Pb  208Pb/204Pb
2000  1000   0              13.0         500   102.951253    13.146154    41.738354

Assume a Stacey and Kramers (1975) second stage model and that you have two sets of igneous rocks which plot along curves defined by uranogenic lead isotope decay with slope of 0.06 and intercepts at 207Pb/204Pb = 14.2 and 15.0

In [20]:
mu974_df

t1    t2  238U/204Pb  206Pb/204Pb  207Pb/204Pb  208Pb/204Pb
3699  3700  3699        9.74    11.154682    12.990659    31.232330
3698  3700  3698        9.74    11.157364    12.993316    31.234659
3697  3700  3697        9.74    11.160045    12.995970    31.236989
3696  3700  3696        9.74    11.162726    12.998621    31.239318
3695  3700  3695        9.74    11.165406    13.001270    31.241647
...    ...   ...         ...          ...          ...          ...
4     3700     4        9.74    18.697257    15.618567    39.095429
3     3700     3        9.74    18.698768    15.618637    39.097368
2     3700     2        9.74    18.700280    15.618707    39.099306
1     3700     1        9.74    18.701791    15.618776    39.101244
0     3700     0        9.74    18.703302    15.618846    39.103182

[3700 rows x 6 columns]

In [21]:
m = 0.06
b1 = 14.2
b2 = 15
t1, t2 = 3699, 0

#t = int(np.log(m+1) / decay_const_235 / 1000000)

t = 604 # This is questionable
df_974_t2_207Pb = mu974_df[mu974_df['t2'] == t].values[0][4]

#mu_b1 = (df_974_t2_207Pb-b1)/(np.exp(decay_const_235*t1)-np.exp(decay_const_235*t2)) # This causes problems...
#mu_b2 = (df_974_t2_207Pb-b2)/(np.exp(decay_const_235*t1)-np.exp(decay_const_235*t2)) # This causes problems...

mu_b1 = 8.41
mu_b2 = 11.99

b2_adj_df = gc.get_PbPb_ratio_data(mu_b2, kappa)
b1_adj_df = gc.get_PbPb_ratio_data(mu_b1, kappa)

b2x = b2_adj_df[b2_adj_df['t2'] == t].values[0][3]
b2y = b2_adj_df[b2_adj_df['t2'] == t].values[0][4]

b1x = b1_adj_df[b1_adj_df['t2'] == t].values[0][3]
b1y = b1_adj_df[b1_adj_df['t2'] == t].values[0][4]
t

604

In [22]:
figure9 = gc.get_figure("207Pb/204Pb - 206Pb/204Pb Curve", "207Pb/204Pb", "206Pb/204Pb", [10,22], [12,17])

gc.plot_uranogenicPb_curve(figure9, mu974_df, "blue", "mu = 9.74")

reg_line1 = Slope(gradient=m, y_intercept=b1, line_color="black", line_dash="dashed")
reg_line2 = Slope(gradient=m, y_intercept=b2, line_color="black", line_dash="dashed")

gc.plot_uranogenicPb_curve(figure9, b2_adj_df, "red", "mu = " + str(mu_b2))
figure9.circle(b2x, b2y)

gc.plot_uranogenicPb_curve(figure9, b1_adj_df, "green", "mu = " + str(mu_b1))
figure9.circle(b1x, b1y)


figure9.add_layout(reg_line1)
figure9.add_layout(reg_line2)

figure9.legend.location = "top_left"
figure9.legend.click_policy="hide"

In [23]:
show(figure9)

What are the model source 238U/204Pb values implied for these two plutons? Determine these graphically.

What 238U/204Pb is required for each of these rock groups to reach the geochron?